name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - azure-swa
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - azure-swa

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '6.0.x'

      - name: Build
        shell: pwsh
        run: .\build.ps1

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_BUSH_0A0CED40F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/SmallsOnline.Blazor.Components.Test/"
          api_location: ""
          output_location: ""
          skip_app_build: true
          

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_BUSH_0A0CED40F }}
          action: "close"
